FROM alpine:3.14

RUN set -x \
    && apk add --update --no-cache \
       ca-certificates \
    && rm -rf /var/cache/apk/*
COPY ucl /usr/local/bin/

EXPOSE 8545 9632 1478

RUN addgroup -S ucl-group \
    && adduser -S -u 1001 ucl-user -G ucl-group -h /home/ucl

USER ucl-user

ENTRYPOINT ["ucl"]
