---
name: CI

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - develop

  pull_request: {}

  workflow_dispatch:
    inputs:
      unit_test:
        description: Unit Tests
        type: boolean
        default: true
      fuzz_test:
        description: Fuzz Tests
        type: boolean
        default: true
      e2e_ibft_test:
        description: E2E IBFT Tests
        type: boolean
        default: true

  workflow_call:
    inputs:
      unit_test:
        description: Unit Tests
        type: boolean
        required: true
      fuzz_test:
        description: Fuzz Tests
        type: boolean
        required: true
      e2e_ibft_test:
        description: E2E IBFT Tests
        type: boolean
        required: true

    outputs:
      build:
        description: Build output
        value: ${{ jobs.build.outputs.workflow_output }}
      lint:
        description: Lint output
        value: ${{ jobs.lint.outputs.workflow_output }}
      unit_test:
        description: Unit Tests output
        value: ${{ jobs.unit_test.outputs.workflow_output }}
      fuzz_test:
        description: Fuzz Tests output
        value: ${{ jobs.fuzz_test.outputs.workflow_output }}
      e2e_ibft_test:
        description: E2E IBFT Tests output
        value: ${{ jobs.e2e_ibft_test.outputs.workflow_output }}

jobs:
  build:
    name: Build Polygon Edge
    uses: ./.github/workflows/build.yml
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch'

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: build
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch'

  unit_test:
    name: Unit Tests
    uses: ./.github/workflows/test.yml
    needs: build
    if: |
      inputs.unit_test ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
      github.event_name == 'schedule'

  fuzz_test:
    name: Fuzz Tests
    uses: ./.github/workflows/fuzz-test.yml
    needs: build
    if: |
      inputs.fuzz_test ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
      github.event_name == 'schedule'

  e2e_ibft_test:
    name: E2E IBFT Tests
    uses: ./.github/workflows/e2e.yaml
    needs: build
    if: |
      inputs.e2e_ibft_test ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
      github.event_name == 'schedule'

  notification:
    name: Notification
    uses: ./.github/workflows/ci-notification.yml
    needs: [build, lint, unit_test, fuzz_test, e2e_ibft_test]
    if: (!cancelled() && github.event_name == 'schedule')
    with:
      build_output: ${{ needs.build.outputs.workflow_output }}
      lint_output: ${{ needs.lint.outputs.workflow_output }}
      unit_test_output: ${{ needs.unit_test.outputs.workflow_output }}
      fuzz_test_output: ${{ needs.fuzz_test.outputs.workflow_output }}
      e2e_ibft_test_output: ${{ needs.e2e_ibft_test.outputs.workflow_output }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
