---
name: Unit Tests
on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      workflow_output:
        description: Unit tests output
        value: ${{ jobs.unit_test.outputs.output_failure }}

jobs:
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    outputs:
      output_failure: ${{ steps.tests_failure.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: "go.mod"

      - name: Install Dependencies
        run: ./setup-ci.sh

      - name: Run Go Test
        run: make test

      - name: Run Go Test Failed
        if: failure()
        id: tests_failure
        run: echo "result=false" >> $GITHUB_OUTPUT
